// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCqXeXq5DymJZ3cs_5fWclgCyZF86fxQ80',
    appId: '1:735331181585:android:85c1e88ac9656dac2dfdb0',
    messagingSenderId: '735331181585',
    projectId: 'ewalletdemo-14129',
    databaseURL: 'https://ewalletdemo-14129-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'ewalletdemo-14129.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDXAt39UI1lFQtk97nis8gHGozrAJ9wtE0',
    appId: '1:735331181585:ios:079200a2d10273f22dfdb0',
    messagingSenderId: '735331181585',
    projectId: 'ewalletdemo-14129',
    databaseURL: 'https://ewalletdemo-14129-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'ewalletdemo-14129.appspot.com',
    iosBundleId: 'com.example.ewalletdemo',
  );
}
